language: node_js
node_js:
  - "4.2"
before_install:
  - npm install -g bower
  - npm install -g gulp-cli
  - npm install
before_script:
  - chmod a+x ./netlify_deploy.sh
script:
  - if [[ "$TRAVIS_BRANCH" == "develop" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then gulp deploy --env=landing.stage.virtuaas.com --config.base_path=//landing.stage.virtuaas.com; fi
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then gulp deploy --env=virtuaas.com --type=production; fi
after_success:
  - ./netlify_deploy.sh